# Prefix 키를 Ctrl+a로 변경 (더 편해요)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# 마우스 지원 활성화
set -g mouse on

# 창 번호를 1부터 시작
set -g base-index 1

# 패널(Pane) 번호를 1부터 시작하도록 설정
set -g pane-base-index 1

# 상태바 색상
set -g status-style bg=black,fg=white

# 패널 번호(display-panes) 표시 시간을 2초로 연장
set -g display-panes-time 2000

#
set -g mode-keys vi

# 설정 리로드 단축키
bind r source-file ~/.config/tmux/tmux.conf

# 화면 분할 시 현재 경로 유지
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# 패널 포커스 이동 (herdr와 동일한 prefix+h/j/k/l)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 동시 입력 단축키 등록
bind-key y set-window-option synchronize-panes\; display-message "Sync: #{?pane_synchronized,ON,OFF}"

# 설정 적용 커맨드: tmux source-file ~/.config/tmux/tmux.conf

# ===================================================
# 상단바 커스텀
# ===================================================
# Pane 상단 바 표시
set -g pane-border-status top
set -g pane-border-lines heavy

# 테두리 색상
set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=#7aa2f7"

# 상단 바 내용
set -g pane-border-format "#{?pane_active,#[bg=#7aa2f7 fg=#1a1b26 bold],#[bg=#3b4261 fg=#a9b1d6]} #{pane_index} #[default] #{?pane_active,#[fg=#7aa2f7 bold],#[fg=#787c99]}#{?#{pane_title},#{pane_title},#{pane_current_command}} "
